app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dash.urls"))
]

dash/urls.py
from django.urls import path
from . import views

app_name = 'imob'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('contextualizacao', views.contextualizacao_page_view, name='contextualizacao'),
    path('dashboard', views.dashboard_page_view, name='dashboard'),
    path('dashboard2', views.dashboard2_page_view, name='dashboard2'),
    path('dashboard3', views.dashboard3_page_view, name='dashboard3'),
    path('dashboard4', views.dashboard4_page_view, name='dashboard4')
]

dash/models.py
from django.db import models

# Create your models here.

dash/views.py
from django.shortcuts import render

# Create your views here.

def home_page_view(request):
    return render(request, 'dash/home.html')

def contextualizacao_page_view(request):
    return render(request, 'dash/contextualizacao.html')

def dashboard_page_view(request):
    return render(request, 'dash/dashboard.html')

def dashboard2_page_view(request):
    return render(request, 'dash/dashboard2.html')

def dashboard3_page_view(request):
    return render(request, 'dash/dashboard3.html')

def dashboard4_page_view(request):
    return render(request, 'dash/dashboard4.html')

dash/templates/dash/contextualizacao.html
{% extends 'dash/layout.html' %} {% block main %} {% load static %}
<div class="contentContextualizacao">
  <h1>Inquérito à Mobilidade nas Áreas Metropolitanas do Porto e de Lisboa</h1>
  <div class="textPrincipalPage">
    <p>
      O Inquérito à Mobilidade realizado em 2017 pelo Instituto Nacional de
      Estatística (INE), teve como principal objetivo caracterizar as
      deslocações realizadas pela população residente, dando resposta
      designadamente às seguintes questões:
    </p>
    <div class="imgboximob">
      <img
        src="{% static 'dash/images/imob.png' %}"
        alt="IMOB logo"
        class="imgimob"
      />
    </div>
    <div class="paddingPoints">
      <p>Como nos deslocamos?</p>
      <p>Quanto tempo demoramos?</p>
      <p>Que distâncias percorremos?</p>
      <p>Que custos temos?</p>
    </div>
    <p>
      A sua realização visou em primeiro lugar corresponder a necessidades de
      informação identificadas pelas Áreas Metropolitanas do Porto e de Lisboa.
      A colaboração a diversos níveis destas entidades foi aliás essencial para
      a concretização desta operação estatística.
    </p>
    <div class="imgboximob2">
      <img
        src="{% static 'dash/images/imob.png' %}"
        alt="IMOB logo"
        class="imgimob"
      />
    </div>
    <p>
      Este inquérito, de realização ocasional, veio permitir a quantificação das
      deslocações dos residentes nas áreas metropolitanas, pese embora diversas
      conclusões virem confirmar a perceção já existente sobre esta temática.
      Subdividiu-se em 3 partes, sobre:
    </p>
    <ul>
      <div>
        <li>
          caracterização da população residente na perspetiva da mobilidade
          (população móvel), incluindo informação socioeconómica e despesas com
          a mobilidade;
        </li>
        <li>
          análise da mobilidade na área metropolitana de acordo com duas
          óticas:<br />
          - deslocações totais realizadas, segundo a residência do
          respondente,<br />
          - deslocações intrametropolitanas (origem e destino na área
          metropolitana);
        </li>
        <li>
          opiniões dos residentes, evidenciando razões para utilização do
          transporte individual e público, bem como a avaliação efetuada sobre
          os transportes públicos.
        </li>
      </div>
    </ul>
    <p>
      Neste trabalho apenas serão utilizados os dados do inquérito relativos à
      Área Metropolitana de Lisboa. Os dados utilizados e o relatório relativo a
      este estudo encontram se
      <a
        href="https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_publicacoes&PUBLICACOESpub_boui=349495406&PUBLICACOESmodo=2&&fbclid=IwAR2QzUZK0mUSEdKySZe1HqmObblKWR62vIyVhtVAAxrQhyNllna-DDfp2bk&xlang=pt"
        target="_blank"
        >aqui</a
      >.
    </p>
  </div>
  <div class="imgamlbox">
    <img
      src="{% static 'dash/images/municipios.png' %}"
      alt="AML logo"
      class="imgaml"
    />
  </div>
  <h1>Área Metropolitana de Lisboa</h1>
  <div class="textPrincipalPage">
    <p>
      A Área Metropolitana de Lisboa (AML) é uma área constituída por 18
      municípios entre as margens norte e sul do Rio Tejo, dos quais fazem
      parte: Alcochete, Almada, Amadora, Barreiro, Cascais, Lisboa, Loures,
      Mafra, Moita, Montijo, Odivelas, Oeiras, Palmela, Seixal, Sesimbra,
      Setúbal, Sintra e Vila Franca de Xira.
    </p>
    <div class="imgamlbox2">
      <img
        src="{% static 'dash/images/municipios.png' %}"
        alt="AML logo"
        class="imgaml"
      />
    </div>
    <p>
      Os Municípios são agrupados em dois grandes grupos, a Grande Lisboa e a
      Península de Setúbal. A área total é de 3 015 km² e residem no local cerca
      de 2.871.133 pessoas, segundo os censos de 2021, o que corresponde a cerca
      de 27% da população nacional.
    </p>
  </div>
  <h1>Objetivos e Metodologia do Trabalho</h1>
  <div class="textPrincipalPage">
    <p>
      Este trabalho foi realizado no âmbito do trabalho final de curso da
      licenciatura em informática de gestão na Universidade Lusófona - Centro
      Universitário de Lisboa, e tem como objetivo conseguir entregar um
      conjunto de visualizações interativas e dinâmicas dos dados disponíveis
      relativos aos transportes na AML, integradas numa página Web. Para
      alcançar este objetivo, será necessário antes fazer um tratamento dos
      dados disponíveis. Pretende-se que os utilizadores deste Website consigam
      analisar e observar os Dashboards que foram criados, e assim, poderão ver
      outro tipo de informações mais facilmente.
    </p>
    <p>
      Para este desenvolvimento foram utilizadas diversas tecnologias, como
      Power BI, que é uma ferramenta de Business Intelligence, de análise de
      dados e análise de negócio criada pela Microsoft, através da qual é
      possível conectar os nossos dados através de diferentes fontes, e
      utilizá-los nesta plataforma unificada e dimensional, onde é possível
      criar relações e desenvolver visualizações, que ajudam na gestão e nas
      tomadas de decisões. Com estas visualizações, é possível criar um conjunto
      de dashboards. Por último, para contruir o website, foi utilizada a
      framework Django, que utiliza Python para a criação das aplicações.
    </p>
    <div class="imgtecnologiasbox">
      <img
        src="{% static 'dash/images/Tecnologias.png' %}"
        alt="Tecnologias"
        class="imgtecnologias"
      />
    </div>
  </div>
  <div class="divButtonBack">
    <a href="{% url 'imob:home' %}"
      ><button type="button" class="buttonBack">
        Voltar à página inicial
      </button></a
    >
  </div>
</div>
{% endblock %}

dash/templates/dash/dashboard.html
{% extends 'dash/layout.html' %} {% block main %}
<div class="content">
  <div class="centeriframe">
    <iframe
      title="Dashboard Mobilidade"
      class="myDiv"
      id="myIframe"
      width="100%"
      height="100%"
      src="https://app.powerbi.com/view?r=eyJrIjoiMjRmMDgwNWUtYmMwOC00N2ZkLWFhMjYtZGU3NjUxMGIzZWZjIiwidCI6IjEzOGNjYzA2LTUxNmItNGU4MS04ODEzLTA2ZmQyNTMxYmRkYyIsImMiOjh9&pageName=ReportSection889394556bbbe91ebaca"
      frameborder="0"
      allowfullscreen="true"
    ></iframe>
  </div>
</div>
{% endblock %}

dash/templates/dash/dashboard2.html
{% extends 'dash/layout.html' %} {% block main %}
<div class="content">
  <div class="centeriframe">
    <iframe
      title="Dashboard Mobilidade"
      class="myDiv"
      id="myIframe"
      width="100%"
      height="100%"
      src="https://app.powerbi.com/view?r=eyJrIjoiMjRmMDgwNWUtYmMwOC00N2ZkLWFhMjYtZGU3NjUxMGIzZWZjIiwidCI6IjEzOGNjYzA2LTUxNmItNGU4MS04ODEzLTA2ZmQyNTMxYmRkYyIsImMiOjh9&pageName=ReportSectiona9928e00bd2a0aa92543"
      frameborder="0"
      allowfullscreen="true"
    ></iframe>
  </div>
</div>
{% endblock %}

dash/templates/dash/dashboard3.html
{% extends 'dash/layout.html' %} {% block main %}
<div class="content">
  <div class="centeriframe">
    <iframe
      title="Dashboard Mobilidade"
      class="myDiv"
      id="myIframe"
      width="100%"
      height="100%"
      src="https://app.powerbi.com/view?r=eyJrIjoiMjRmMDgwNWUtYmMwOC00N2ZkLWFhMjYtZGU3NjUxMGIzZWZjIiwidCI6IjEzOGNjYzA2LTUxNmItNGU4MS04ODEzLTA2ZmQyNTMxYmRkYyIsImMiOjh9&pageName=ReportSection52d1ce563ac01d70a543"
      frameborder="0"
      allowfullscreen="true"
    ></iframe>
  </div>
</div>
{% endblock %}

dash/templates/dash/dashboard4.html
{% extends 'dash/layout.html' %} {% block main %}
<div class="content">
  <div class="centeriframe">
    <iframe
      title="Dashboard Mobilidade"
      class="myDiv"
      id="myIframe"
      width="100%"
      height="100%"
      src="https://app.powerbi.com/view?r=eyJrIjoiMjRmMDgwNWUtYmMwOC00N2ZkLWFhMjYtZGU3NjUxMGIzZWZjIiwidCI6IjEzOGNjYzA2LTUxNmItNGU4MS04ODEzLTA2ZmQyNTMxYmRkYyIsImMiOjh9&pageName=ReportSection33520f32c18d39ac481a"
      frameborder="0"
      allowfullscreen="true"
    ></iframe>
  </div>
</div>
{% endblock %}

dash/templates/dash/home.html
{% extends 'dash/layout.html' %} {% block main %} {% load static %}
<div class="contentHome">
  <div class="texthome">
    <h1 class="textcentered">Mobilidade na AML</h1>
    <p style="padding: 0px; margin: 0px; font-size: 18px">
      Dados sobre a mobilidade na Área Metropolitana de Lisboa, com base no
      Inquérito à Mobilidade IMOB realizado pelo INE em 2017
    </p>
  </div>
</div>
<div class="contentContextualizacao">
  <div class="textPrincipalPage">
    <p>Este website é constituido por 6 separadores:</p>
    <ul>
      <li class="paddingListHome">
        <b>Início</b>: Página onde se encontra. É a página inicial do website.
      </li>
      <li class="paddingListHome">
        <b>Contextualização</b>: Apresentação do que foi o Inquérito à
        Mobilidade (IMOB), apresentação de o que é a Área Metropolitana de
        Lisboa e quais os concelhos que a constituem, e objetivos e metodologia
        utilizada para este trabalho.
      </li>
      <li class="paddingListHome">
        <b>Informações população</b>: Neste serparador são apresentados os
        primeiros dashboards, com informações relativamente aos Municípios e as
        caracteristicas da população que reside nos mesmos.
      </li>
      <li class="paddingListHome">
        <b>Mobilidade na AML</b>: Neste separador encontram se diversas
        informações relativas aos tipos de transporte, deslocações, duração e
        distância das deslocações, o tipo das deslocações, distribuição e
        densidades.
      </li>
      <li class="paddingListHome">
        <b>Avaliação e Opiniões</b>: Aqui é onde se encontram as avaliações e
        opiniões dos inquiridos, de acordo com um conjunto de perguntas
        realizadas.
      </li>
      <li class="paddingListHome">
        <b>Correlações entre variáveis</b>: Por último, está um separador que
        apresenta algumas correlações que foram realizadas com os dados
        apresentados nos outros separadores.
      </li>
    </ul>
  </div>
</div>
{% endblock %}

dash/templates/dash/imobpage.html
{% extends 'dash/layout.html' %} {% block main %} {% load static %}
<div class="content">
  <h1>Inquérito à Mobilidade nas Áreas Metropolitanas do Porto e de Lisboa</h1>
  <div class="textPrincipalPage">
    <p>
      O Inquérito à Mobilidade 2017 teve como objetivo principal caracterizar as
      deslocações realizadas pela população residente, dando resposta
      designadamente às seguintes questões:
    </p>
    <div class="paddingPoints">
      <p>Como nos deslocamos?</p>
      <p>Quanto tempo demoramos?</p>
      <p>Que distâncias percorremos?</p>
      <p>Que custos temos?</p>
    </div>
    <p>
      A realização visou em primeiro lugar corresponder a necessidades de
      informação identificadas pelas Áreas Metropolitanas do Porto e de Lisboa.
      A colaboração a diversos níveis destas entidades foi aliás essencial para
      a concretização desta operação estatística.
    </p>
    <div class="imgboximob">
      <img
        src="{% static 'dash/images/imob.png' %}"
        alt="IMOB logo"
        class="imgimob"
      />
    </div>
    <p>
      Este inquérito, de realização ocasional, veio permitir a quantificação das
      deslocações dos residentes nas áreas metropolitanas, pese embora diversas
      conclusões virem confirmar a perceção já existente sobre esta temática.
      Subdividiu-se em 3 partes, sobre:
    </p>
    <ul>
      <div>
        <li>
          caracterização da população residente na perspetiva da mobilidade
          (população móvel), incluindo informação socioeconómica e despesas com
          a mobilidade;
        </li>
        <li>
          análise da mobilidade na área metropolitana de acordo com duas
          óticas:<br />
          - deslocações totais realizadas, segundo a residência do
          respondente,<br />
          - deslocações intrametropolitanas (origem e destino na área
          metropolitana);
        </li>
        <li>
          opiniões dos residentes, evidenciando razões para utilização do
          transporte individual e público, bem como a avaliação efetuada sobre
          os transportes públicos.
        </li>
      </div>
    </ul>
    <p>
      Neste trabalho apenas serão utilizados os dados do inquérito relativos à
      Área Metropolitana de Lisboa. Os dados utilizados e o relatório relativo a
      este estudo encontram se
      <a
        href="https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_publicacoes&PUBLICACOESpub_boui=349495406&PUBLICACOESmodo=2&&fbclid=IwAR2QzUZK0mUSEdKySZe1HqmObblKWR62vIyVhtVAAxrQhyNllna-DDfp2bk&xlang=pt"
        target="_blank"
        >aqui</a
      >.
    </p>
  </div>
</div>
{% endblock %}

dash/templates/dash/layout.html
<!DOCTYPE html>
{% load static %} {% with url_name=request.resolver_match.url_name %}
<html lang="pt">
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="icon"
      href="https://www.tmlmobilidade.pt/wp-content/uploads/2022/02/cropped-favicon_tml-192x192.png"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="Martim Teixeira" />
    <link rel="stylesheet" href="{% static 'dash/css/style.css' %}" />
    <title>IMOB Dashboard</title>
  </head>
  <body>
    <header>
      <div class="sidebar" id="myTopnav">
        <div class="">
          <a class="image" href="{% url 'imob:home' %}"
            ><img
              src="{% static 'dash/images/aml.png' %}"
              alt="AML logo"
              class="imglogo"
            />
            <img
              src="{% static 'dash/images/TML.png' %}"
              alt="AML logo"
              class="imgTML2"
              style="padding-bottom: 18px"
            />
          </a>
        </div>
        <a
          href="{% url 'imob:home' %}"
          class="{% if url_name == 'home' %}active{% endif %}"
          >Início</a
        >
        <a
          href="{% url 'imob:contextualizacao' %}"
          class="{% if url_name == 'contextualizacao' %}active{% endif %}"
          >Contextualização</a
        >
        <div class="dropdown">
          <button onclick="changepage()" class="dropdown-btn" id="button1">
            Informações sobre população
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-container" id="container-drop">
            <a href="#" onclick="pbFunc('page1')" id="page1" class=""
              >População e Municípios</a
            >
            <a href="#" onclick="pbFunc('page2')" id="page2" class=""
              >Caracterização população</a
            >
            <a href="#" onclick="pbFunc('page3')" id="page3" class=""
              >Despesas população</a
            >
          </div>
          <div class="dropdown">
            <button onclick="changepage()" class="dropdown-btn" id="button2">
              Mobilidade na <br />AML
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-container" id="container-drop2">
              <a href="#" onclick="pbFunc2('page4')" id="page4"
                >Tipo transporte</a
              >
              <a href="#" onclick="pbFunc2('page5')" id="page5"
                >Deslocações diárias</a
              >
              <a href="#" onclick="pbFunc2('page6')" id="page6"
                >Tipo de estacionamento</a
              >
              <a href="#" onclick="pbFunc2('page7')" id="page7"
                >Duração e distância deslocações</a
              >
              <a href="#" onclick="pbFunc2('page8')" id="page8"
                >Deslocações intramunicipais</a
              >
              <a href="#" onclick="pbFunc2('page9')" id="page9"
                >Deslocações intermunicipais</a
              >
              <a href="#" onclick="pbFunc2('page10')" id="page10"
                >Destino deslocações intermunicipais</a
              >
              <a href="#" onclick="pbFunc2('page11')" id="page11"
                >Distribuição deslocações</a
              >
              <a href="#" onclick="pbFunc2('page12')" id="page12"
                >Densidade deslocações</a
              >
            </div>
          </div>
          <div class="dropdown">
            <button onclick="changepage()" class="dropdown-btn" id="button3">
              Avaliação e opiniões
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-container" id="container-drop3">
              <a href="#" onclick="pbFunc3('page13')" id="page13"
                >Automóvel vs Transportes públicos</a
              >
              <a href="#" onclick="pbFunc3('page14')" id="page14"
                >Transportes públicos</a
              >
              <a href="#" onclick="pbFunc3('page15')" id="page15"
                >Utilização automóvel</a
              >
              <a href="#" onclick="pbFunc3('page16')" id="page16"
                >Utilização transportes públicos</a
              >
              <a href="#" onclick="pbFunc3('page17')" id="page17"
                >Avaliação transportes públicos</a
              >
            </div>
          </div>
          <div class="dropdown">
            <button onclick="changepage()" class="dropdown-btn" id="button4">
              Correlações entre variáveis
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-container" id="container-drop4">
              <a href="#" onclick="pbFunc4('page18')" id="page18"
                >Matriz de correlação</a
              >
              <a href="#" onclick="pbFunc4('page19')" id="page19"
                >Outras correlações</a
              >
            </div>
          </div>
        </div>
        <div class="space"></div>
        <div class="imagebox" style="background-color: white">
          <img
            src="{% static 'dash/images/TML.png' %}"
            alt="AML logo"
            class="imgTML"
          />
        </div>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()"
          >&#9776;</a
        >
      </div>
    </header>
    <main>{% block main %} {% endblock main %}</main>
    <footer>
      <p>
        Martim Teixeira - Trabalho Final de Curso<br />
        Licenciatura em Informática de Gestão, Universidade Lusófona ©2023
      </p>
    </footer>
  </body>
  <script src="{% static 'dash/javascript/script.js' %}"></script>
</html>
{% endwith %}